import cron from "node-cron";
import Groq from "groq-sdk";
import { GoogleGenerativeAI } from "@google/generative-ai";
import CodingContest from "../models/CodingContest.js";
import User from "../models/User.js";

const getGroq = () => new Groq({ apiKey: process.env.GROQ_API_KEY });
const getGemini = () => new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

const extractJSON = (text, isArray = false) => {
  const s = isArray ? "[" : "{";
  const e = isArray ? "]" : "}";
  const si = text.indexOf(s);
  const ei = text.lastIndexOf(e);
  if (si !== -1 && ei > si) text = text.substring(si, ei + 1);
  else text = text.replace(/```json/g, "").replace(/```/g, "").trim();
  return JSON.parse(text);
};

// Generates an AI Coding Contest
export const generateDailyAIContest = async () => {
  try {
    console.log("🤖 Auto generating Daily AI Coding Contest...");

    // Find an admin user to be the creator
    const admin = await User.findOne({ role: { $in: ["superadmin", "admin"] } });
    if (!admin) {
      console.error("No admin found to create the AI contest.");
      return;
    }

    // Determine the tech trend for the day
    const topics = ["Data Structures & Algorithms", "Dynamic Programming", "Graph Theory", "Advanced Web3 Concepts", "Database Optimization", "System Design Coding", "Backend API Security"];
    const languages = ["javascript", "python", "cpp", "java"];
    
    // Pick a random topic and language
    const randomTopic = topics[Math.floor(Math.random() * topics.length)];
    const randomLanguage = languages[Math.floor(Math.random() * languages.length)];

    // 1. Generate Meta
    const metaPrompt = `
You are an expert contest organizer. Generate metadata for a daily 24-hour coding contest.
Topic: ${randomTopic}

Generate a JSON object with this EXACT structure:
{
  "title": "Daily AI Challenge: ${randomTopic}",
  "subtitle": "Test your skills against AI generated problems every 24 hours",
  "description": "Welcome to the Daily AI Challenge. Today's focus is on ${randomTopic}. The problems are completely generated by AI to test your algorithmic thinking. Good luck!",
  "company": "OneStop AI",
  "difficulty": "Intermediate",
  "tags": ["daily", "ai-generated", "coding", "${randomTopic}"],
  "rules": [
    "No plagiarism allowed.",
    "Contest lasts 24 hours.",
    "Submissions are evaluated securely."
  ],
  "prizes": [
    { "rank": 1, "title": "🥇 First Place", "amount": "100 XP / Profile Badge", "perks": ["Featured on Leaderboard"] },
    { "rank": 2, "title": "🥈 Second Place", "amount": "50 XP", "perks": ["Featured on Leaderboard"] }
  ]
}
Return ONLY valid JSON. Start immediately with {.
`;

    let metaText = "";
    try {
      const groq = getGroq();
      const resp = await groq.chat.completions.create({
        messages: [{ role: "user", content: metaPrompt }],
        model: "llama-3.3-70b-versatile",
        temperature: 0.75,
        max_tokens: 1500,
      });
      metaText = resp.choices[0]?.message?.content || "";
    } catch (e) {
      const gemini = getGemini();
      const model = gemini.getGenerativeModel({ model: "gemini-1.5-flash" });
      const result = await model.generateContent(metaPrompt);
      metaText = result.response.text();
    }
    const metaData = extractJSON(metaText, false);


    // 2. Generate Problems (2 problems for daily)
    const probPrompt = `
You are a Senior Engineering Director. Design 2 coding contest problems for a daily coding challenge.
Topic: ${randomTopic}
Difficulty Level: Intermediate
Programming Language: ${randomLanguage}

Generate EXACTLY 2 problems.
- Problem 1: Warm-up (Easy)
- Problem 2: Core challenge (Medium)

For each problem, generate this JSON format:
{
  "title": "Problem Title",
  "description": "Full problem statement with examples",
  "difficulty": "Easy",
  "constraints": ["1 <= n <= 10^5"],
  "inputFormat": "Input format description",
  "outputFormat": "Output format description",
  "starterCode": "// Language: ${randomLanguage}\\nfunction solve(input) {\\n  // Your solution here\\n}",
  "testCases": [
    { "input": "input1", "expectedOutput": "output1", "isHidden": false, "marks": 25 },
    { "input": "input2", "expectedOutput": "output2", "isHidden": true, "marks": 25 }
  ],
  "points": 100
}
Return ONLY a valid JSON array. Start immediately with [.
`;

    let probText = "";
    try {
      const groq = getGroq();
      const resp = await groq.chat.completions.create({
        messages: [{ role: "user", content: probPrompt }],
        model: "llama-3.3-70b-versatile",
        temperature: 0.7,
        max_tokens: 4000,
      });
      probText = resp.choices[0]?.message?.content || "";
    } catch (e) {
      const gemini = getGemini();
      const model = gemini.getGenerativeModel({ model: "gemini-1.5-flash" });
      const result = await model.generateContent(probPrompt);
      probText = result.response.text();
    }
    const problemsData = extractJSON(probText, true);

    // Beautiful predefined banners for auto-generated AI contests
    const defaultBanners = [
      "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=1200", // code on screen
      "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=1200", // matrix
      "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?auto=format&fit=crop&q=80&w=1200", // cyberpunk tech
      "https://images.unsplash.com/photo-1504639725590-34d0984388bd?auto=format&fit=crop&q=80&w=1200", // abstract tech network
    ];
    const randomBanner = defaultBanners[Math.floor(Math.random() * defaultBanners.length)];

    // Create Contest
    const contest = new CodingContest({
      ...metaData,
      mode: "ai",
      createdBy: admin._id,
      durationHours: 24,
      startAt: new Date(), // Starts immediately when generated
      isPublished: true,
      languages: [randomLanguage, "javascript", "python", "cpp", "java"], // allow multiple
      problems: problemsData,
      status: "live",
      banner: { url: randomBanner, publicId: "ai-auto-generated" },
    });

    await contest.save();
    console.log(`✅ Daily AI Contest created successfully! ID: ${contest._id}`);
  } catch (error) {
    console.error("❌ Failed to generate Daily AI Contest:", error);
  }
};

// Initialize Cron Jobs
export const initCronJobs = () => {
  // Run every 24 hours at 00:00 (midnight server time)
  // Format: "minute hour dayOfMonth month dayOfWeek"
  cron.schedule("0 0 * * *", () => {
    generateDailyAIContest();
  });

  console.log("⏰ AI Daily Coding Contest Cron Job initialized (Runs at 00:00).");
};
